name: Publish Docker images

on:
  - push

jobs:
  build-docker-image:
    strategy:
      matrix:
        version: [1.19.2, 1.19]
    uses: ./.github/workflows/build-mc-server.yaml
    with:
      mc-server-version: ${{ matrix.version }}