name: Publish Docker images

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        version: [1.19.2, 1.19]
    uses: ./.github/workflows/build-mc-server.yaml
    with:
      mc-server-version: 1.19.2