name: Build and publish Minecraft server image

on:
  workflow_call:
    inputs:
      mc-server-version:
        required: true
        type: string
    

jobs:
  build-and-push:
    if: ${{ always() }}
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image with Minecraft server version ${{ inputs.mc-server-version }}
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            serverfile=https://serverjars.com/api/fetchJar/vanilla/vanilla/${{ inputs.mc-server-version }}
            minecraftversion=${{ inputs.mc-server-version }}
          tags: ghcr.io/instantmc/client:mc-${{ inputs.mc-server-version }}